"""add_preferences_and_agent_context

Revision ID: ac722fa4af6b
Revises: fff40ccfd1a9
Create Date: 2025-11-23 13:13:12.919131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac722fa4af6b'
down_revision: Union[str, None] = 'fff40ccfd1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firebase_uid', sa.String(), nullable=False),
    sa.Column('agent_name', sa.String(), nullable=False),
    sa.Column('context_type', sa.String(), nullable=True),
    sa.Column('context_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_context_firebase_uid'), 'agent_context', ['firebase_uid'], unique=False)
    op.create_index(op.f('ix_agent_context_id'), 'agent_context', ['id'], unique=False)
    op.add_column('conversations', sa.Column('message_id', sa.String(), nullable=True))
    op.add_column('conversations', sa.Column('conversation_metadata', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'conversations', ['message_id'])
    op.add_column('users', sa.Column('preferences', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'preferences')
    op.drop_constraint(None, 'conversations', type_='unique')
    op.drop_column('conversations', 'conversation_metadata')
    op.drop_column('conversations', 'message_id')
    op.drop_index(op.f('ix_agent_context_id'), table_name='agent_context')
    op.drop_index(op.f('ix_agent_context_firebase_uid'), table_name='agent_context')
    op.drop_table('agent_context')
    # ### end Alembic commands ###
