// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFdX5EO8YSmSnIa4zmpF9J_IHe7-CxfUY',
    appId: '1:159176107427:web:da13d92d19d4098aec2616',
    messagingSenderId: '159176107427',
    projectId: 'agent-x-lxix',
    authDomain: 'agent-x-lxix.firebaseapp.com',
    storageBucket: 'agent-x-lxix.firebasestorage.app',
    measurementId: 'G-XSWRSQG15F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVFZ4cNtMSeK6gAY3wnKRzgptDeWmI-4A',
    appId: '1:159176107427:android:d066ff1eb399a109ec2616',
    messagingSenderId: '159176107427',
    projectId: 'agent-x-lxix',
    storageBucket: 'agent-x-lxix.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4YHs_oEzwzOdbhJ-SAh1ScuPsji7jrN4',
    appId: '1:159176107427:ios:bdd9d8d7a6d5b1caec2616',
    messagingSenderId: '159176107427',
    projectId: 'agent-x-lxix',
    storageBucket: 'agent-x-lxix.firebasestorage.app',
    androidClientId: '159176107427-cehba0mt95nml7bti5rnvdluencvtqj6.apps.googleusercontent.com',
    iosClientId: '159176107427-73r52den2kr1i854k2gqk1bq1s1cr8k3.apps.googleusercontent.com',
    iosBundleId: 'com.idksam.agentx',
  );
}
